---
ssh_port: 22
rhel: "rhel8"
common_node_config_options:
  - dest: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: Port {{ ssh_port | default('22') }}
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?UseDNS'
    line: 'UseDNS no'
    validate: sshd -t -f %s

  - dest: /etc/sudoers
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

  - dest: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: 'Defaults    !requiretty'
    validate: visudo -cf %s


ec2_wait: true
ec2_info:
  juniper:
    size: c4.xlarge
    ami: "{{juniper_ami | default(omit)}}"
    os: junos
    username: ec2-user
    volume:
      - device_name: /dev/sda1
        volume_type: io1
        iops: 1000
        volume_size: 40
        delete_on_termination: true
  cisco:
    size: t2.medium
    ami: "{{cisco_ami | default(omit)}}"
    os: ios
    username: ec2-user
  arista:
    size: c5.xlarge
    ami: "{{arista_ami | default(omit)}}"
    os: eos
    username: ec2-user
    filter: "*VEOSRouter*"
  checkpoint_mgmt:
    owners: 679593333241
    filter: 'Check Point CloudGuard IaaS BYOL*R80.30*'
    architecture: x86_64
    size: m5.xlarge
    ami: "{{ checkpoint_mgmt_ami| default(omit) }}"
    username: admin
  checkpoint_gw:
    owners: 679593333241
    filter: 'Check Point CloudGuard IaaS GW*BYOL*R80.30*'
    architecture: x86_64
    size: c5.large
    ami: "{{ checkpoint_gw_ami| default(omit) }}"
    username: admin
  windows_ws:
    owners: 679593333241
    filter: 'Windows_Server-2016-English-Full-Base*'
    size: m5.xlarge
    ami: "{{ windows_ws_ami| default(omit) }}"
    username: Administrator
  # Look for owner 309956199498 to find official Red Hat AMIs
  rhel8-tower:
    owners: 309956199498
    size: t2.medium
    os_type: linux
    disk_space: 20
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
  rhel8:
    owners: 309956199498
    size: t2.large
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
  rhel7:
    owners: 309956199498
    size: t2.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-7.7_HVM_GA-20190723-x86_64-1-Access2-GP2'
    username: ec2-user
    python_interpreter: '/usr/bin/python'
  f5node:
    owners: 679593333241
    size: t2.large
    os_type: linux
    disk_space: 40
    architecture: x86_64
    filter: 'F5 Networks Prelicensed Hourly BIGIP-13.1*Good 25MBPS*'
    username: admin
  splunk_enterprise:
    owners: 309956199498
    size: c4.4xlarge
    os_type: linux
    disk_space: 200
    architecture: x86_64
    filter: 'RHEL-7.7_HVM_GA-20190723-x86_64-1-Access2-GP2'
    username: ec2-user
    python_interpreter: '/usr/bin/python'
  netapp:
    owners: 679593333241
    size: t2.medium
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'OnCommand_Cloud_Manager_3.7.0_Marketplace*'
    username: ec2-user
  qradar:
    owners: 324218975267
    size: t2.2xlarge
    os_type: linux
    disk_space: 300
    architecture: x86_64
    filter: 'AnsibleSecurity-QRadarCE*'
    username: ec2-user
    python_interpreter: '/usr/bin/python'
  skylight_windows_ws:
    filter: 'Windows_Server-2016-English-Full-Base*'
    size: t3.medium
  skylight_windows_instance:
    filter: 'Windows_Server-2019-English-Core-Base*'
    size: t3.medium
  skylight_rhel7_gitlab:
    filter: 'RHEL-7.6_HVM_GA*x86_64*'
    size: t2.xlarge
    username: ec2-user
  skylight_rhel8_gitlab:
    owners: 309956199498
    filter: 'RHEL-8*HVM-*Hourly*'
    size: t2.xlarge
    username: ec2-user
    architecture: x86_64
  attendance_host:
    owners: 309956199498
    size: t2.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
